
clion.bundle.docker.image.linux=registry.jetbrains.team/p/clion/containers/pkgbuild-linux-centos-7:6-amd64-staging-3-arm64-staging
clion.bundle.docker.image.mingw=registry.jetbrains.team/p/clion/containers/pkgbuild-mingw:6-amd64-staging
clion.bundle.docker.image.mingw-toolchain=registry.jetbrains.team/p/clion/containers/pkgbuild-mingw-toolchain:1-amd64-staging
clion.bundle.docker.image.aarch64-mingw=registry.jetbrains.team/p/clion/containers/pkgbuild-aarch64-mingw-windows-arm64:6-amd64-staging
