
clion.bundle.docker.image.linux=registry.jetbrains.team/p/clion/containers/pkgbuild-linux-centos-7:1-amd64-1-arm64
clion.bundle.docker.image.mingw=registry.jetbrains.team/p/clion/containers/pkgbuild-mingw:1-amd64
clion.bundle.docker.image.mingw-toolchain=registry.jetbrains.team/p/clion/containers/pkgbuild-mingw-toolchain:1-amd64
clion.bundle.docker.image.aarch64-mingw=registry.jetbrains.team/p/clion/containers/pkgbuild-aarch64-mingw-windows-arm64:1-amd64
